//
//  EventViewModel.swift
//  ScreenBoom
//
//  Created by Michael Tanious on 2/10/18.
//  Copyright © 2018 WMWiOS. All rights reserved.
//

import Foundation
import FirebaseCore
import FirebaseDatabase


let firebaseNodeNames = FirebaseNodeNames.sharedInstance
enum Result<T> {
  case Success(T)
  case Failure(String)
}

typealias ConfigureWithEventCompletionHandler = (_:Result<Void>) -> Void

class EventManager: NSObject {
  
  let firebaseNodeNames = FirebaseNodeNames()
  var event: Event?
  
  func configureWithEvent(event:Event, completion:ConfigureWithEventCompletionHandler? = nil) {
    checkIfEventExists(newEvent: event, completion: { eventExists, snapshot  in
      if !eventExists {
        // if the event is not exists set the value
        self.event = event
        completion?(Result.Success(()))
      } else {
        // run the completion block if we have one
        // and pass the result
        completion?(Result.Failure("Event is Already Exist"))
      }
    })
  }
  
  // check if event is already exist
  func checkIfEventExists (newEvent: Event, completion:(@escaping (Bool, Event?) -> Void)) {
    FireBaseManager.sharedInstance.REF_Event.child(newEvent.eventName).observeSingleEvent(of: .value, with: { (snapshot) in
      if snapshot.exists() {
        guard let eventCodeFirebase = snapshot.childSnapshot(forPath: "code").value as? String,
            let eventTypeFirebase = snapshot.childSnapshot(forPath: "type").value as? String,
            let eventIsLiveFirebase = snapshot.childSnapshot(forPath: "islive").value as? String,
            let eventuserIDFirebase = snapshot.childSnapshot(forPath: "userid").value as? String
            else {
                // if event name is exist and we couldn't retrive the data
                 completion(true,nil )
                return
        }
        
        let event = Event(eventName: newEvent.eventName,
                          eventIsLive: eventIsLiveFirebase,
                          eventType: EventType(rawValue: eventTypeFirebase)!,
                          eventCode: eventCodeFirebase,
                          userID: eventuserIDFirebase)
        
        completion(true,event)
      } else {
        completion(false,nil )
      }
    })
  }
  
  
  // addEvent method will store the event in the fireBase
  // case failure will return error string
  // case success will return the random code for that event so we can store it in the eventDetail Node
  // the random code is 5 random character generated by string extension
  func addEvent(event: Event, completion:(@escaping(Result<String>) -> Void)) {
    
    let eventCode = String.random()
    
    let eventFIRReferance = Database.database().reference().child("Event").child(event.eventName)
    
    eventFIRReferance.setValue(
      [firebaseNodeNames.eventNodeTypeChild : event.eventType.rawValue,
       firebaseNodeNames.eventNodeIsLiveChild : event.eventIsLive ,
       firebaseNodeNames.eventNodeCodeChild : eventCode,
       firebaseNodeNames.eventUserIDChild : event.userID ],
      withCompletionBlock: { (error, response) in
      guard error == nil else {
        
        completion(Result.Failure((error?.localizedDescription)!))
        return
      }
      
      completion(Result.Success(eventCode))
    })
  }

  /// update the Event islive node with yes or no
  func updateEvenIsLive(event: Event, isLive: String, completion:(@escaping(Result<Void>) -> Void)) {
 Database.database().reference().child(firebaseNodeNames.eventNode).child(event.eventName).child(firebaseNodeNames.eventNodeIsLiveChild).setValue(isLive) { (error, _) in
      if error != nil {
        completion(Result.Failure((error?.localizedDescription)!))
      } else {
        completion(Result.Success(()))
      }
    }
  }
  
  /// update the Event type node with text, photo or animation
  func updateEvenType(event: Event, eventType: EventType, completion:(@escaping(Result<Void>) -> Void)) {
  Database.database().reference().child(firebaseNodeNames.eventNode).child(event.eventName).child(firebaseNodeNames.eventNodeTypeChild).setValue(eventType.rawValue) { (error, _) in
      if error != nil {
        completion(Result.Failure((error?.localizedDescription)!))
      } else {
        completion(Result.Success(()))
      }
    }
  }
  
  /// update the Event node with new Event
  func updateEvenType(event: Event, completion:(@escaping(Result<Void>) -> Void)) {
    Database.database().reference().child(firebaseNodeNames.eventNode).child(event.eventName).updateChildValues([firebaseNodeNames.eventNodeTypeChild : event.eventType, firebaseNodeNames.eventNodeIsLiveChild: event.eventIsLive]) { (error, _) in
      if error != nil {
        completion(Result.Failure((error?.localizedDescription)!))
      } else {
        completion(Result.Success(()))
      }
   }
  }
  
  /// remove Event
  func removeEvent(event: Event,completion:(@escaping(Result<Void>) -> Void )) {
    Database.database().reference().child(firebaseNodeNames.eventNode).child(event.eventName).removeValue { (error, _) in
      if error != nil {
        completion(Result.Failure((error?.localizedDescription)!))
      } else {
        completion(Result.Success(()))
      }

    }
  }
  
  // get Event
  func getEvent(eventName: String,completion:(@escaping(Result<Event>) -> Void )) {
    Database.database().reference().child(firebaseNodeNames.eventNode).child(eventName).observeSingleEvent(of: .value) { (eventSnapShot) in
      if let eventValue = eventSnapShot.value as? [String:String] {
        guard let eventIsLive = eventValue[self.firebaseNodeNames.eventNodeIsLiveChild],
              let eventType = eventValue[self.firebaseNodeNames.eventNodeTypeChild],
              let eventCode = eventValue[self.firebaseNodeNames.eventNodeCodeChild] else {
          completion(Result.Failure("Event Not Found"))
          return }
        let event = Event(eventName: eventName, eventIsLive: eventIsLive, eventType: EventType(rawValue: eventType) ?? .Unknown, eventCode: eventCode)
        completion(Result.Success(event))
      }
    }
    completion(Result.Failure("Event Not Found"))
  }
}









