# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScreenBoom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScreenBoom
	
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Canvas'
pod 'SDWebImage'
pod 'GiphyCoreSDK'
pod 'IQKeyboardManagerSwift'
pod 'Google-Mobile-Ads-SDK'


end
